import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import ReduxWrapper from '@/store/ReduxWrapper';

import { ThemeProvider } from '@/components/providers/theme-provider';
import { ModalProvider } from '@/components/providers/modal-provider';
import { NavigationSidebar } from '@/components/navigation/NavigationSidebar';
import HeaderItem from '@/components/header/HeaderItem/page';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxWrapper>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(inter.className, 'bg-white dark:bg-[#313338]')}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="chatter-theme"
          >
            <ModalProvider />
            <div className="h-full">
              <div className="w-full h-[72px] z-30 flex-col fixed inset-y-0 bg-white dark:bg-[#313338]">
                <HeaderItem />
              </div>
              <div className="mt-16">{children}</div>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ReduxWrapper>
  );
}
